// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func POC() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article><header><strong>1. HTMX fragment swap</strong></header><p>Submit a URL; the server fetches it and returns an HTML fragment with status + latency. This is the round-trip pattern the real ping loop will use.</p><form hx-post=\"/poc/ping\" hx-target=\"#poc-ping-result\" hx-swap=\"innerHTML\" hx-disable=\"#poc-ping-submit\"><fieldset role=\"group\"><input type=\"url\" name=\"url\" placeholder=\"https://example.com\" required value=\"https://example.com\"> <button id=\"poc-ping-submit\" type=\"submit\">Ping</button></fieldset></form><div id=\"poc-ping-result\"></div></article><article><header><strong>2. HTMX polling</strong></header><p>Server clock, refreshed every second via <code>hx-trigger=\"every 1s\"</code>. Open DevTools → Network to watch the requests.</p><kbd id=\"poc-clock\" hx-get=\"/poc/time\" hx-trigger=\"load, every 1s\" hx-swap=\"innerHTML\">…</kbd></article><article x-data=\"{ open: false }\"><header><strong>3. Alpine ephemeral state</strong></header><p>The dialog below is opened/closed entirely client-side via Alpine — no server round-trip.</p><button type=\"button\" x-on:click=\"open = true\">Open dialog</button> <dialog x-bind:open=\"open\"><article><header><button aria-label=\"Close\" rel=\"prev\" x-on:click=\"open = false\"></button><p><strong>Hello from Alpine</strong></p></header><p>If you can read this, Alpine 3.15.11 is loaded and reactive.</p></article></dialog></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("POC — Uptime Tracker").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
